// src/routes/ptik/+page.svelte
<script>
import { formatDate } from "$lib/utils";

let {data} = $props()

</script>

<div class="navbar bg-neutral shadow-lg/25">
  <a href="/" class="btn btn-ghost text-xl h-full block flex">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5 8.25 12l7.5-7.5" />
    </svg>
    Back
  </a>
</div>

<div class="overflow-x-auto">
  <table class="table">
    <thead>
        <tr>
            <th>NIM</th>
            <th>Nama</th>
            <th>Tempat, Tanggal Lahir</th>
        </tr>
    </thead>
    <tbody>
        {#each data.mahasiswa as mahasiswa}
            <tr>
                <td>K35240{mahasiswa.nim.toString().padStart(2, '0')}</td>
                <td>{mahasiswa.nama}</td>
                <td>{mahasiswa.tempat_lahir + ', ' + formatDate(mahasiswa.tanggal_lahir)}</td>
            </tr>
        {/each}
    </tbody>
  </table>
</div>

// src/pages/logged/Ptik.jsx
import { A } from "@solidjs/router";
import { createSignal, For } from "solid-js";

import { getAllPtik } from "../../lib/api";
import { formatDate } from "../../lib/utils";

export default function Ptik({data}){
    const [mahasiswa, setMahasiswa] = createSignal([])

    getAllPtik().then(res => {
        if (res.status != 200) return
        res.json().then(json => {
            setMahasiswa(json)
        })
    })

    return <>
        <div class="navbar bg-neutral shadow-lg/25">
        <A href="/" class="btn btn-ghost text-xl h-full">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5 8.25 12l7.5-7.5" />
            </svg>
            Back
        </A>
        </div>

        <div class="overflow-x-auto">
        <table class="table">
            <thead>
                <tr>
                    <th>NIM</th>
                    <th>Nama</th>
                    <th>Tempat, Tanggal Lahir</th>
                </tr>
            </thead>
            <tbody>
                <For each={mahasiswa()}>
                    {(item, index) => (
                        <tr>
                            <td>K35240{item.nim.toString().padStart(2, '0')}</td>
                            <td>{item.nama}</td>
                            <td>{item.tempat_lahir + ', ' + formatDate(item.tanggal_lahir)}</td>
                        </tr>
                    )}
                </For>
                {/* {data.map((mahasiswa, index) => {
                    return <tr key={index}>
                    </tr>
                })} */}
            </tbody>
        </table>
        </div>
    </>
}
